name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: TeePlunder
          config_timezone: Europe/Berlin
          committer_message: "chore: update metrics"
          template: classic
          base: header, activity, community, repositories, metadata 
          plugin_introduction: yes

          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes

          plugin_calendar: yes
          plugin_calendar_limit: 5
